### ISSUE TITLE
No need to check if characters are common

### ISSUE THREAD

**Issue by shantanuo** [mtrevisan/HunLinter#1] opened 2019-10-02 14:04 UTC
This affix works correctly as expected:

```
SET UTF8

SFX P Y 1
SFX P णे लेल्या/Aacd णे
```
_____

This affix file does not work because the 3rd, 4th and 5th columns are the same. This is also expected:

```
SET UTF8

SFX P Y 1
SFX P णे णे णे
```

Reading error: Characters in common between removed and added part: 'SFX P णे णे णे', line 4
_____

But the following file does not work and that is a problem.

```
SET UTF8

SFX P Y 1
SFX P णे णार णे
```

Reading error: Characters in common between removed and added part: 'SFX P णे णार णे', line 4

You are checking only the first character in column 3 and 4. If it matches you throw the error. But you should compare the “entire” 3rd and 4th column, (Not just first character).

In fact there is no need of that check at all. Simply follow the rule!

**Comment by mtrevisan** [comment] 2019-10-02 15:04
I'll try putting
```SFX P े ार णे```
in an aff file and load it into LibreOffice, and see if it works. I'll report you back on the result.

**Comment by mtrevisan** [comment] 2019-10-02 15:17
With this rule
```SFX P े ार णे```
instead of
```SFX P णे णार णे```
LibreOffice has no problems at all: all the expected productions are produced.
How did you say that the file does not works?

If I don't hear again from you I considered this report not a bug and close it.
Thank you for reporting

**Comment by shantanuo** [comment] 2019-10-02 15:51
May be I did not report the issue correctly. There is no issue with LibreOffice. Your Java program is not able to open that file and throws an exception.

**Comment by mtrevisan** [comment] 2019-10-02 17:36
Ok, now I understand your issue,
Well, my program does exactly this: it'll report every error (or strange things) that are in the aff/dic files, so, it's kind of normal it throws an exception, because there is (at least) one issue in those files.
Once you correct all the issues my application finds, you'll be able to correctly open the files.

**Comment by shantanuo** [comment] 2019-10-03 01:25
Thanks for your reply. The third file mentioned in this bug report has NO ISSUES at all. It is a standard suffix rule used in Marathi Language.  The "strange thing" for one language can be fine for other languages! So please provide an option to open the file without so called "error checking" functionality.

**Comment by mtrevisan** [comment] 2019-10-03 07:02
Can you better explain yourself? The .aff file format is cross-language, is valid for all languages. Can you tell me a case when this kind of error you reported could not be valid?
I've implemented a two kind of checks. One is valid for all languages, one can be customized for each specific language. In this way each language can have its specific error controls.
To day I've implemented only the controls specific to the venetan language because that is the language I'm currently interested in. For all the other languages there are a general checker that checks for general errors (or "strange things").
Besides that, the rule ```SFX P े ार णे``` has the very same validity of ```SFX P णे णार णे```, so I don't see the problem you are reporting. Am I wrong?
Maybe this kind of things could be reported as "warning" and not "blocking errors" because they are not properly an error that prevents subsequently processing. I'll think about that.

**Comment by mtrevisan** [comment] 2020-05-11 09:37
Separated the errors into true errors (that prevents further operations) and warnings (that let further operations function anyway).

**Closed by mtrevisan** 2020-05-11 09:37 UTC
